### ISSUE TITLE
Add possibility to not throw error for one level depth

### ISSUE THREAD

**Issue by vladshcherbin** [HeroProtagonist/eslint-plugin-module-resolver#10]
It would be nice to have an option for an error not to be thrown for some level of depth import. I need 1, maybe more is needed for someone else.

For example:

```js
// Component is Forms/Input/Input.js
// I would like to import FieldError which is 1 level high
import FieldError from '../FieldError'
```

In this example I don't want to import it like this: `Client/components/Forms/FieldError`.

What do you think?

**Comment by HeroProtagonist** [comment]
@vladshcherbin yea this makes sense to me. I will have time to check it out later this week or if you want to take a stab at it. I can look at what you do. Thanks for using my library!

**Comment by vladshcherbin** [comment]
@HeroProtagonist sure, take all the time you need for it. I'll add a comment in this place and change it later.

Thank you for the library, so far everything is working great :)

**Comment by HeroProtagonist** [comment]
@vladshcherbin please checkout `v0.11.0` 

I added an option to accomplish this. You can see the https://github.com/HeroProtagonist/eslint-plugin-module-resolver/blob/master/docs/rules/use-alias.md#rule-options for how to use it.

Let me know how it works 👍

**Comment by vladshcherbin** [comment]
@HeroProtagonist not sure why, but 0.11.0 gives me an error:

```
Oops! Something went wrong! :(

ESLint: 5.16.0.
ESLint couldn't find the plugin "eslint-plugin-module-resolver". This can happen for a couple different reasons:

...
```

I checked it in `node_module` and I believe you forgot to build files, there is no `dist` folder in release 🤔

**Comment by HeroProtagonist** [comment]
@vladshcherbin yea the build failed but it still published :(

`0.12.0` should be fine 👍

**Comment by vladshcherbin** [comment]
@HeroProtagonist everything is working as expected, thank you! 🎉
