### ISSUE TITLE
Make the rule fixable

### ISSUE THREAD

**Issue by HeroProtagonist** [HeroProtagonist/eslint-plugin-module-resolver#19]
See the api [here](https://eslint.org/docs/developer-guide/working-with-rules-deprecated#applying-fixes)

**Comment by GeorgySerga** [comment]
Can I work on this? :)

**Comment by jaysbytes** [comment]
Hi, @GeorgySerga How it is work on that going 😊 ?

**Comment by GeorgySerga** [comment]
Hey @jaysbytes I started experimenting with that and might have some progress stashed, but I've decided to make a step back to refactor some things, like here https://github.com/HeroProtagonist/eslint-plugin-module-resolver/pull/41 and (less of refactor) here https://github.com/HeroProtagonist/eslint-plugin-module-resolver/pull/42 . You can pick this up if you want to, I wouldn't have time this month either way :)

**Comment by HeroProtagonist** [comment]
closed with [v1.0.0](https://github.com/HeroProtagonist/eslint-plugin-module-resolver/releases/tag/v1.0.0)
