### ISSUE TITLE
Rule doesn't flag subdirectories of aliases after v1.2.0

### ISSUE THREAD

**Issue by as-zlynn-philipps** [HeroProtagonist/eslint-plugin-module-resolver#241]
- eslint-plugin-module-resolver >=1.3.0
- eslint v7.32.0
- @babel/core v7.17.9
- babel-plugin-module-resolver v4.1.0
- node v16.14.2
- Windows 10

## Steps To Reproduce

1. Install eslint-plugin-module-resolver >=1.3.0
2. Configure an alias like `{ components: './src/components' }` in either `.babelrc` or `.eslintrc`
3. Reference a file like `import blah from '../../components/blah'`
4. Run ESLint

## The current behavior

There is a warning/error for imports from `../../components`, but not `../../components/blah`.

## The expected behavior

There should be a warning or error for imports from `../../components/blah`.

**Comment by as-zlynn-philipps** [comment]
The autofix on Windows also adds backslashes like `components\blah` when it should be `components/blah`.

**Comment by HeroProtagonist** [comment]
Hi @as-zlynn-philipps,

Would you be able to see if the tests pass on your windows machine? I created #242 to add windows as part of the circle testing

**Comment by HeroProtagonist** [comment]
@as-zlynn-philipps This should be fixed in `v1.5.0`
