### ISSUE TITLE
Add a better file path resolution

### ISSUE THREAD

**Issue by vladshcherbin** [HeroProtagonist/eslint-plugin-module-resolver#3]
Hey,

Thank you for the plugin. The idea is nice, however I can't make it work even for basic things. For example:

*alias* is: `ClientMain: './src/client/main'`
*import* is: `import App from '../../../client/main/components/App'`

I checked examples (which have only easiest name resolutions) and code, seems like in the example above, the alias Set will be `{ 'src/client/main' }` and [here](https://github.com/HeroProtagonist/eslint-plugin-module-resolver/blob/master/lib/rules/use-alias.js#L40-L41) it will check first import part (`client`) in this Set, so `'src/client/main' !== 'client'`.

However, this code is working fine with `import App from 'ClientMain/components/App'`.

It would be great to have a better file path resolution because now it's hard to make it work.

**Comment by HeroProtagonist** [comment]
@vladshcherbin thanks for the feedback. I am going to do a few updates to this library soon and release a new version. Let me know if there are other improvements you would want to see

**Comment by HeroProtagonist** [comment]
Hi @vladshcherbin,

I pushed some changes and now have `v0.9.0` that should address what you mention. 

Thanks a lot for your feedback as it made the file resolution a lot better. 
Please let me know if this fixed your issue and other ones you encounter.

**Comment by vladshcherbin** [comment]
@HeroProtagonist hey, I've tested it today and it fully works. Everything seems to be working as expected.

Thank you 🎉
