### ISSUE TITLE
Support default aliases & crash when no aliases provided

### ISSUE THREAD

**Issue by jayu** [HeroProtagonist/eslint-plugin-module-resolver#45]
In projects where I'm using `module-resolver` I often skip alias definition. Module resolver by default treats each root's subdirectory as an alias which is very convenient. I can just have absolute paths to all my modules. This is my default config 

```js
module.exports = {
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        alias: {}, // plugin crashes without this prop
        extensions: ['.js', '.ts', '.tsx', '.json'],
      },
    ],
  ],
};

```

However, this plugin only supports only user-defined aliases. In addition, if `alias` prop is skipped in the config, plugin crashes.

I would like to address that, but I'm not sure If I should extend existing rule `use-alias` or define a new rule like `use-default-alias`. After shallow code analysis, I think the first option would be easier to implement since I will just extend aliases paths. In the second option, I will probably have to exclude default aliases from the `use-alias` rule since it may try to fix the same error in different ways. BTW after that, I will work on making rules fixable, this is what I need in the project.

Let me know @HeroProtagonist and I will tackle that.

**Comment by HeroProtagonist** [comment]
If it is easy to make it that when the alias is `{}` or `undefined` we fallback to the default that the library uses then I think that would be preferably to making a new rule. If it makes more sense to make a new rule thats fine too 👍

**Comment by jaysbytes** [comment]
I need to check but I assume that default aliases are always an option even if the user specifies custom ones. If custom aliases override default is even easier to implement. I will check that.

**Comment by jaysbytes** [comment]
After playing around with different configurations of `babel-plugin-module-resolver` I understood a few  things
- each subdirectory of directories from `root` options is treated as an alias
- default and not-overridable value for `root` is `node_modules` directory
- if the user specifies neither `root` filed nor `alias` field aliasing does not work (alias set is empty)
- to use `babel-plugin-module-resolver` with `TypeScript` additional configuration in ts config is needed. But it does not impact on how modules are mapped in JS, it impacts how TS resolves files for type-checking. 

So my conclusion is that the plugin should treat all aliases equally, so it should all be implemented within the same rule
