### ISSUE TITLE
Node 10? 

### ISSUE THREAD

**Issue by yarian** [HeroProtagonist/eslint-plugin-module-resolver#7]
Does this have to actually run on Node v10+?

**Comment by HeroProtagonist** [comment]
@yarian no, it actually should be fine to run on versions a lot lower because of transpilation with [babel](https://github.com/HeroProtagonist/eslint-plugin-module-resolver/blob/master/.babelrc#L1-L3).

I should remove that field in the package.json

**Comment by yarian** [comment]
Thanks! Appreciate you looking into it.
